pr:  # Trigger a build on every PR.
  branches:
    include:
      - '*'  # Must quote since "*" is a YAML reserved character

jobs:
- job: TestHarnessWindows
  displayName: 'Test Harness Windows'
  variables:
    TEST_HARNESS: "true"
    TRAVIS_OS_NAME: "windows"
    TRAVIS: "true"
    TRAVIS_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)
    TRAVIS_PULL_REQUEST_SHA: $(Build.SourceVersion)
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 360

  steps:
    - checkout: self
      persistCredentials: true
      path: enigma-dev
  
    - powershell: |
        Get-Service 'Windows Audio'
        Start-Service 'Windows Audio'
        Get-Service 'Windows Audio'
      displayName: 'Enable Windows Audio'
    - script: C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "printenv"
      displayName: 'printenv'
    - script: |
        (robocopy $(Build.SourcesDirectory) C:\enigma-dev /COPYALL /E) ^& IF %ERRORLEVEL% LEQ 1 exit 0

    - script: |
        enigma_bootstrap.bat
        python3 -m pip install --upgrade Pillow
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "lcov"
      displayName: 'Bootstrap enigma and install pillow'
    - script: |
        Get-Service: 'Windows Audio'  
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "pacman -Q && mkdir test-harness-out"
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "./test-runner.exe"
      displayName: 'Run Test-Runner'
      workingDirectory: C:\enigma-dev
    - task: PublishBuildArtifacts@1
      displayName: 'Push Build Artifacts'
      inputs:
        pathtoPublish: 'C:\enigma-dev\test-harness-out'
