     
      
pr:  # Trigger a build on every PR.
  branches:
    include:
      - '*'  # Must quote since "*" is a YAML reserved character



jobs:
- job: TestHarnessWindows
  displayName: 'Test Harness Windows'
  variables:
    TEST_HARNESS: "true"
    TRAVIS_OS_NAME: "windows"
    TRAVIS: "true"
    TRAVIS_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)
    TRAVIS_PULL_REQUEST_SHA: $(Build.SourceVersion)
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 360

  steps:
    - checkout: self
      persistCredentials: true
      path: enigma-dev
      
    - script: |
        (robocopy $(Build.SourcesDirectory) C:\enigma-dev /COPYALL /E) ^& IF %ERRORLEVEL% LEQ 1 exit 0
      displayName: 'Stage ENIGMA'
  
    - powershell: |
        Get-Service 'Windows Audio'
        Start-Service 'Windows Audio'
        Get-Service 'Windows Audio'
    - script: python3 -m pip install --upgrade Pillow
      displayName: Pillow install
    - script: dxdiag /dontskip /whql:off /t c:\dxdiagraw.txt
    - script: C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "pacman -Q"
      displayName: Default Installed packages
    - script: |
        C:\enigma-dev\enigma_bootstrap.bat
      displayName: Install mingw stuff
  
    - script: C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "pacman -Q"
      displayName: Installed Packages
      workingDirectory: C:\enigma-dev
    
    - script: C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "./test-runner.exe"
      displayName: Running Tests
      #mingw-w64-x86_64-gtest
      #mingw-w64-x86_64-imagemagick
      #mingw-w64-x86_64-jq 1.6-5
      #mingw-w64-x86_64-libmodplug
      #lcov

      env:
        _IMGUR_CLIENT_ID: $(imgur_client_id)
        _BOT_COMMENT_TOKEN: $(bot_comment_token)
        _BOT_PUSH_ON_GREEN_TOKEN: $(bot_push_on_green_token)
        _CODECOV_UPLOAD_TOKEN: $(codecov_upload_token)
      
    - task: PublishBuildArtifacts@1
      displayName: 'Push Build Artifacts'
      inputs:
        pathtoPublish: C:\dxdiagraw.txt
        artifactName: Test-Harness-Png
        


- job: Windows
  displayName: 'Windows'
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 360
  variables:
    COMPILER: gcc
    OUTPUT: /tmp/test.exe

  steps:
    - checkout: self
      persistCredentials: true
      path: enigma-dev
     
    - script: git clone --depth 1 https://github.com/enigma-dev/enigma-android.git android
      displayName: 'Clone Android Repo'

    - script: |
        (robocopy $(Build.SourcesDirectory) C:\enigma-dev /COPYALL /E) ^& IF %ERRORLEVEL% LEQ 1 exit 0
      displayName: 'Stage ENIGMA'
    
    - script: |
        C:\enigma-dev\enigma_bootstrap.bat
      displayName: 'Bootstrap ENIGMA Install'

    - script: |
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "export PLATFORM=%PLATFORM%; ./ci-build.sh && ./share_logs.sh"
      displayName: 'Run Mode'
      workingDirectory: C:\enigma-dev
      env:
        MODE: Run
        PLATFORM: Win32
        GRAPHICS: Direct3D9
        AUDIO: None
        COLLISION: None
        NETWORK: None
        WIDGETS: None
        EXTENSIONS: "None"

    - script: |
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "export PLATFORM=%PLATFORM%; ./ci-build.sh && ./share_logs.sh"
      displayName: 'Compile Mode'
      workingDirectory: C:\enigma-dev
      env:
        MODE: Compile
        PLATFORM: Win32
        GRAPHICS: Direct3D9
        AUDIO: None
        COLLISION: None
        NETWORK: None
        WIDGETS: None
        EXTENSIONS: "None"

    - script: |
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "export PLATFORM=%PLATFORM%; ./ci-build.sh && ./share_logs.sh"
      displayName: 'Windows APIs & Extensions'
      workingDirectory: C:\enigma-dev
      env:
        GRAPHICS: Direct3D11 
        AUDIO: DirectSound
        WIDGETS: Win32 
        EXTENSIONS: "DirectShow,WindowsTouch,XInput,MediaControlInterface,FileDropper,IniFilesystem,ExternalFuncs"
        PLATFORM: Win32
        MODE: Debug
        COLLISION: None
        NETWORK: None

    - script: |
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "export PLATFORM=%PLATFORM%; ./ci-build.sh && ./share_logs.sh"
      displayName: 'OpenGL1 & OpenAL'
      workingDirectory: C:\enigma-dev
      env:
        GRAPHICS: OpenGL1 
        AUDIO: OpenAL
        PLATFORM: Win32
        MODE: Debug
        COLLISION: None
        NETWORK: None
        WIDGETS: None
        EXTENSIONS: "None"

    - script: |
        C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "export PLATFORM=SDL; ./ci-build.sh && ./share_logs.sh"
      displayName: 'OpenGLES & SDL'
      workingDirectory: C:\enigma-dev
      env:
        GRAPHICS: OpenGLES3
        PLATFORM: Win32
        MODE: Debug
        AUDIO: None
        COLLISION: None
        NETWORK: None
        WIDGETS: None
        EXTENSIONS: "None"

    - script: |
        cmd /c C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -here -lc "rm -rf /tmp/*"
        "%TMP%\nsis-binary-7208-3\Bin\makensis" /V4 "C:/enigma-dev/enigma.nsi"
      displayName: 'Build Installer'

    - task: PublishBuildArtifacts@1
      displayName: 'Push Build Artifacts'
      inputs:
        pathtoPublish: 'C:\Windows\Temp\ENIGMA-installer.exe'
        artifactName: ENIGMA-installer
